# Generated by Django 4.2.27 on 2026-02-03 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('idreal1', models.BigIntegerField(db_column='IdReal1', primary_key=True, serialize=False)),
                ('zedd', models.TextField(blank=True, db_column='Zedd', null=True)),
                ('cd', models.DateTimeField(blank=True, db_column='CD', null=True)),
                ('un', models.TextField(blank=True, db_column='UN', null=True)),
                ('idtanam', models.BigIntegerField(blank=True, db_column='IdTanam', null=True)),
                ('idprod', models.TextField(blank=True, db_column='IdProd', null=True)),
                ('idactions', models.TextField(blank=True, db_column='IdActions', null=True)),
                ('raod', models.FloatField(blank=True, null=True)),
                ('discount_price', models.FloatField(blank=True, db_column='discount_price', null=True)),
                ('sachuqari', models.FloatField(blank=True, db_column='Sachuqari', null=True)),
                ('std_price', models.FloatField(blank=True, db_column='std_price', null=True)),
                ('tanxa', models.FloatField(blank=True, db_column='Tanxa', null=True)),
                ('prod', models.TextField(blank=True, db_column='Prod', null=True)),
                ('idprodt', models.BigIntegerField(blank=True, db_column='IdProdT', null=True)),
                ('idprodg', models.BigIntegerField(blank=True, db_column='IdProdG', null=True)),
                ('desc1', models.TextField(blank=True, db_column='Desc1', null=True)),
                ('prodt', models.TextField(blank=True, db_column='ProdT', null=True)),
                ('prodg', models.TextField(blank=True, db_column='ProdG', null=True)),
                ('actions', models.TextField(blank=True, db_column='Actions', null=True)),
                ('tanam', models.TextField(blank=True, db_column='Tanam', null=True)),
            ],
            options={
                'db_table': 'sales_main_web',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_locations', models.JSONField(blank=True, default=list)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
